#connect to the storage account
Install-PackageProvider -Name "Nuget" -Force
install-module az.storage -Force

$context=New-AzStorageContext -ConnectionString "BlobEndpoint=<Endpoint as generated by your storage account. Read and List permissions are required>"

Get-AzStorageContainer -Context $context appsources | Get-AzStorageBlobContent -Blob "Blob parent Folder/Blob Folder/Blob Name" -Destination $env:TEMP

Expand-Archive -Path "$env:temp\Blob parent Folder/Blob Folder/Blob Name" -DestinationPath "$env:PROGRAMFILES\Destination Dir\Content" -Force
